#!/bin/bash

# same configuration as applied in ./entrypoint
set -o errexit
set -o pipefail
set -o nounset

# Make sure to apply any migrations available.
echo "[DJANGO] Running migrations..."
python /app/manage.py migrate
# TODO: maybe run gunicorn
echo "[DJANGO] Starting server"
gunicorn mastf.MASTF.wsgi:application --bind 0.0.0.0:$DJANGO_PORT --workers 4 --threads 4
