# Generated by Django 4.1.7 on 2023-04-13 07:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('permission_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256, null=True)),
                ('protection_level', models.CharField(blank=True, max_length=256)),
                ('dangerous', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=256, null=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('risk', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('md5', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('sha256', models.CharField(default='', max_length=64)),
                ('sha1', models.CharField(default='', max_length=40)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('file_size', models.CharField(default='', max_length=50)),
                ('file_path', models.CharField(max_length=2048, null=True)),
                ('internal_name', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FindingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('default_severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('risk', models.TextField()),
                ('mitigation', models.TextField()),
                ('article', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, null=True)),
                ('artifact_id', models.CharField(max_length=512, null=True)),
                ('group_id', models.CharField(max_length=512, null=True)),
                ('type', models.CharField(choices=[('Github', 'Github'), ('Dart', 'Dart'), ('Cordova', 'Cordova'), ('Flutter', 'Flutter'), ('None', 'None')], default=mastf.MASTF.utils.enum.PackageType['NONE'], max_length=256)),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Undefined', 'Undefined')], default=mastf.MASTF.utils.enum.Platform['UNKNOWN'], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('tags', models.CharField(max_length=4096, null=True)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=mastf.MASTF.utils.enum.Visibility['PRIVATE'], max_length=256)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['INFO'], max_length=256)),
                ('inspection_type', models.CharField(choices=[('Simple', 'Simple'), ('Advanced', 'Advanced')], default=mastf.MASTF.utils.enum.InspectionType['SIMPLE'], max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=32, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('scan_type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('risk_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.file')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.project')),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.CharField(blank=True, max_length=2048)),
                ('sys_path', models.CharField(max_length=1024, null=True)),
                ('language', models.CharField(max_length=32, null=True)),
                ('file_name', models.CharField(max_length=512, null=True)),
                ('file_size', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(null=True)),
                ('state', models.CharField(choices=[('To Verify', 'To Verify'), ('Confirmed', 'Confirmed'), ('Urgent', 'Urgent'), ('Not Exploitable', 'Not Exploitable'), ('Proposed not exploitable', 'Proposed not exploitable')], default=mastf.MASTF.utils.enum.State['TO_VERIFY'], max_length=256)),
                ('status', models.CharField(max_length=256, null=True)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=mastf.MASTF.utils.enum.Visibility['PUBLIC'], max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('task_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('celery_id', models.CharField(max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.team'),
        ),
        migrations.CreateModel(
            name='PermissionFinding',
            fields=[
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(null=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.apppermission')),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageVulnerability',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=256, null=True)),
                ('version', models.CharField(max_length=512, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.package')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('finding_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256)),
                ('discovery_date', models.DateField(null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvss', models.FloatField(default=0)),
                ('tracker_count', models.IntegerField(default=0)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.file')),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('dependency_uuid', models.CharField(max_length=72, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('Transitive', 'Transitive'), ('Direct', 'Direct')], default=mastf.MASTF.utils.enum.Relation['DIRECT'], max_length=256)),
                ('outdated', models.CharField(max_length=512, null=True)),
                ('version', models.CharField(blank=True, max_length=512)),
                ('license', models.CharField(max_length=256, null=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.package')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.project')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
