# Generated by Django 4.1.7 on 2023-03-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('md5', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('sha256', models.CharField(default='', max_length=64)),
                ('sha1', models.CharField(default='', max_length=40)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('file_size', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('tags', models.CharField(max_length=4096, null=True)),
                ('visibility', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=32, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('scan_type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('risk_level', models.CharField(max_length=256, null=True)),
                ('scanner', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, null=True)),
                ('language', models.CharField(max_length=256, null=True)),
                ('severity', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=256, null=True)),
                ('source_file', models.CharField(max_length=256, null=True)),
                ('source_line', models.CharField(max_length=256, null=True)),
                ('discovery_date', models.DateField(null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.scan')),
            ],
        ),
        migrations.AddField(
            model_name='scan',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.user'),
        ),
        migrations.AddField(
            model_name='scan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.project'),
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.project')),
            ],
        ),
    ]
