# Generated by Django 4.2.1 on 2023-07-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperInfo",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "developer_id",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=512)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("store_name", models.CharField(blank=True, max_length=32)),
                ("app_id", models.CharField(blank=True, max_length=512)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("score", models.FloatField(default=0.0)),
                ("installs", models.CharField(blank=True, default="0", max_length=128)),
                ("price", models.CharField(blank=True, max_length=256)),
                ("url", models.URLField(blank=True)),
                ("release_date", models.CharField(blank=True, max_length=256)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="component",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MASTF.apppermission",
            ),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="is_contextual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="package",
            name="is_tracker",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="scantask",
            name="celery_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("group_id", "artifact_id"),
                name="unique_package_groupid_artifactid",
            ),
        ),
        migrations.AddField(
            model_name="storeinfo",
            name="developer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MASTF.developerinfo",
            ),
        ),
        migrations.AddField(
            model_name="details",
            name="store_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MASTF.storeinfo",
            ),
        ),
    ]
