# Generated by Django 4.2.1 on 2023-07-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MASTF.apppermission",
            ),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="is_contextual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="package",
            name="is_tracker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("group_id", "artifact_id"),
                name="unique_package_groupid_artifactid",
            ),
        ),
    ]
