# Generated by Django 4.1.7 on 2023-03-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='template',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectscanner',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='template',
        ),
        migrations.DeleteModel(
            name='AccountData',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Finding',
        ),
        migrations.DeleteModel(
            name='FindingTemplate',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionFinding',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
        migrations.DeleteModel(
            name='ProjectScanner',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
    ]
