# Generated by Django 4.1.7 on 2023-03-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
