# Generated by Django 4.1.7 on 2023-04-16 13:43

from django.db import migrations, models
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Github', 'Github'), ('Dart', 'Dart'), ('Cordova', 'Cordova'), ('Flutter', 'Flutter'), ('Native', 'Native'), ('None', 'None')], default=mastf.MASTF.utils.enum.PackageType['NONE'], max_length=256),
        ),
    ]
