# Generated by Django 4.2.1 on 2023-05-18 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MASTF", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("version", models.CharField(blank=True, max_length=12, null=True)),
                ("sha1", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=255)),
                ("issuer", models.TextField(blank=True)),
                ("subject", models.TextField(blank=True)),
                ("hash_algorithm", models.TextField(blank=True)),
                ("signature_algorithm", models.TextField(blank=True)),
                ("serial_number", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CipherSuite",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("cipher_uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("recommended", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataCollectionGroup",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("dc_uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("group", models.CharField(max_length=256)),
                (
                    "protection_level",
                    models.CharField(
                        choices=[("Private", "Private"), ("Public", "Public")],
                        default=mastf.MASTF.utils.enum.DataProtectionLevel["PUBLIC"],
                        max_length=256,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("env_id", models.UUIDField(primary_key=True, serialize=False)),
                ("allow_registration", models.BooleanField(default=True)),
                ("allow_teams", models.BooleanField(default=True)),
                ("max_projects", models.IntegerField(default=100000)),
                ("max_teams", models.IntegerField(default=10000)),
                ("max_bundles", models.IntegerField(default=10000)),
                ("first_start", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostTemplate",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("template_id", models.UUIDField(primary_key=True, serialize=False)),
                ("domain_name", models.CharField(max_length=256)),
                ("ip_address", models.CharField(max_length=32, null=True)),
                ("owner", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IntentFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=1024)),
                ("action", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TLS",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("tls_uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=256, null=True)),
                ("recommended", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="details",
            name="file",
        ),
        migrations.RemoveField(
            model_name="package",
            name="type",
        ),
        migrations.AddField(
            model_name="account",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="apppermission",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="apppermission",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="dependency",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dependency",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="app_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="app_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="app_version",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="icon",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="target_sdk",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="custom_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finding",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="internal_id",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="meta_cvss",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="meta_cwe",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="meta_masvs",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="findingtemplate",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("Github", "Github"),
                    ("Dart", "Dart"),
                    ("Cordova", "Cordova"),
                    ("Flutter", "Flutter"),
                    ("Native", "Native"),
                    ("Maven", "Maven"),
                    ("None", "None"),
                ],
                default=mastf.MASTF.utils.enum.PackageType["NONE"],
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="packagevulnerability",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="packagevulnerability",
            name="severity",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                    ("Info", "Info"),
                    ("Secure", "Secure"),
                    ("None", "None"),
                ],
                default=mastf.MASTF.utils.enum.Severity["NONE"],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="packagevulnerability",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="permissionfinding",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="permissionfinding",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scanner",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="scantask",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scantask",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="scantask",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="snippet",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="updated_on",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Regular", "Regular"),
                    ("External", "External"),
                ],
                default=mastf.MASTF.utils.enum.Role["REGULAR"],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="apppermission",
            name="group",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="apppermission",
            name="identifier",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="apppermission",
            name="protection_level",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="license",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="outdated",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="finding",
            name="discovery_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="finding",
            name="scanner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.scanner",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.findingtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="findingtemplate",
            name="template_id",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="artifact_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="group_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="permissionfinding",
            name="discovery_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="permissionfinding",
            name="scanner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.scanner",
            ),
        ),
        migrations.AlterField(
            model_name="permissionfinding",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.findingtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("Public", "Public"),
                    ("Private", "Private"),
                    ("Internal", "Internal"),
                ],
                default=mastf.MASTF.utils.enum.Visibility["PRIVATE"],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="discovery_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="scanner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.scanner",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MASTF.findingtemplate",
            ),
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "host_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("Invalid", "Invalid"),
                            ("Tracker", "Tracker"),
                            ("Malware", "Malware"),
                            ("Ok", "Ok"),
                            ("Not Set", "Not Set"),
                        ],
                        default=mastf.MASTF.utils.enum.HostType["NOT_SET"],
                        max_length=256,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                ("ip", models.CharField(max_length=32, null=True)),
                ("port", models.IntegerField(default=0)),
                ("protocol", models.CharField(max_length=256, null=True)),
                ("country", models.CharField(max_length=256, null=True)),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                (
                    "collected_data",
                    models.ManyToManyField(
                        related_name="hosts", to="MASTF.datacollectiongroup"
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MASTF.scan",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MASTF.scanner",
                    ),
                ),
                (
                    "snippet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MASTF.snippet",
                    ),
                ),
                (
                    "suites",
                    models.ManyToManyField(
                        related_name="hosts", to="MASTF.ciphersuite"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MASTF.hosttemplate",
                    ),
                ),
                (
                    "tlsversions",
                    models.ManyToManyField(related_name="hosts", to="MASTF.tls"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cid",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=2048)),
                ("is_exported", models.BooleanField(default=False)),
                ("is_protected", models.BooleanField(default=True)),
                ("is_launcher", models.BooleanField(default=False)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Activity", "Activity"),
                            ("Service", "Service"),
                            ("Receiver", "Receiver"),
                            ("Provider", "Provider"),
                            ("Application", "Application"),
                        ],
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "intent_filters",
                    models.ManyToManyField(
                        related_name="components", to="MASTF.intentfilter"
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MASTF.scanner"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("bundle_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("tags", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                            ("Info", "Info"),
                            ("Secure", "Secure"),
                            ("None", "None"),
                        ],
                        default=mastf.MASTF.utils.enum.Severity["NONE"],
                        max_length=32,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(related_name="bundles", to="MASTF.project"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="details",
            name="certificates",
            field=models.ManyToManyField(
                related_name="details", to="MASTF.certificate"
            ),
        ),
    ]
