# Generated by Django 4.2.1 on 2023-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0002_component_permission_findingtemplate_is_contextual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scantask",
            name="celery_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
