# Generated by Django 4.1.7 on 2023-04-17 07:02

from django.db import migrations, models
import django.db.models.deletion
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0002_alter_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, null=True)),
                ('port', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('langitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=256)),
                ('protection_level', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default=mastf.MASTF.utils.enum.DataProtectionLevel['PUBLIC'], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=256, null=True)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('Invalid', 'Invalid'), ('Tracker', 'Tracker'), ('Ok', 'Ok'), ('Not Set', 'Not Set')], default=mastf.MASTF.utils.enum.HostType['NOT_SET'], max_length=256)),
                ('url', models.URLField(max_length=2048, null=True)),
                ('collected_data', models.ManyToManyField(related_name='hosts', to='MASTF.datacollectiongroup')),
                ('connections', models.ManyToManyField(related_name='hosts', to='MASTF.connectioninfo')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('snippet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet')),
                ('suites', models.ManyToManyField(related_name='hosts', to='MASTF.ciphersuite')),
                ('tlsversions', models.ManyToManyField(related_name='hosts', to='MASTF.tls')),
            ],
        ),
    ]
