# Generated by Django 4.1.7 on 2023-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0002_alter_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('host_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=256)),
                ('ip_adress', models.CharField(max_length=32, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
