# Generated by Django 4.2.1 on 2023-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0002_certificate_ciphersuite_datacollectiongroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="findingtemplate",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
    ]
