# Generated by Django 4.1.7 on 2023-03-31 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MASTF', '0002_remove_details_scan_remove_finding_scan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('tags', models.CharField(max_length=4096, null=True)),
                ('visibility', models.CharField(max_length=32, null=True)),
                ('risk_level', models.CharField(max_length=16, null=True)),
                ('inspection_type', models.CharField(default='simple', max_length=32)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
