# Generated by Django 4.1.7 on 2023-04-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0002_ciphersuite_connectioninfo_datacollectiongroup_tls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectioninfo',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
