# Generated by Django 4.1.7 on 2023-04-01 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MASTF', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('permission_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256, null=True)),
                ('protection_level', models.CharField(blank=True, max_length=256)),
                ('dangerous', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=256, null=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('risk', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FindingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=256, null=True)),
                ('risk', models.TextField()),
                ('mitigation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_uuid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=32, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('scan_type', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('risk_level', models.CharField(max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.project')),
            ],
        ),
    ]
