# Generated by Django 4.2.1 on 2023-05-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0003_findingtemplate_is_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="file",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="MASTF.file"
            ),
        ),
    ]
