# Generated by Django 4.1.7 on 2023-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0003_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
