# Generated by Django 4.1.7 on 2023-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0003_ciphersuite_connectioninfo_datacollectiongroup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
