# Generated by Django 4.1.7 on 2023-04-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MASTF', '0004_apppermission_findingtemplate_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scan',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.project'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(max_length=256, null=True)),
                ('severity', models.CharField(max_length=32)),
                ('source_file', models.CharField(max_length=256, null=True)),
                ('source_line', models.CharField(max_length=256, null=True)),
                ('discovery_date', models.DateField(null=True)),
                ('scanner', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.project')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(max_length=256, null=True)),
                ('severity', models.CharField(max_length=32)),
                ('source_file', models.CharField(max_length=256, null=True)),
                ('source_line', models.CharField(max_length=256, null=True)),
                ('discovery_date', models.DateField(null=True)),
                ('scanner', models.CharField(max_length=256, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('md5', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('sha256', models.CharField(default='', max_length=64)),
                ('sha1', models.CharField(default='', max_length=40)),
                ('file_name', models.CharField(default='', max_length=256)),
                ('file_size', models.CharField(default='', max_length=50)),
                ('file_path', models.CharField(max_length=2048, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.project')),
            ],
        ),
    ]
