# Generated by Django 4.1.7 on 2023-04-20 08:39

from django.db import migrations, models
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0004_host_scanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='connections',
        ),
        migrations.AddField(
            model_name='host',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='protocol',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='protection_level',
            field=models.CharField(choices=[('AppPredictor', 'AppPredictor'), ('Appop', 'Appop'), ('Companion', 'Companion'), ('Configurator', 'Configurator'), ('Dangerous', 'Dangerous'), ('Development', 'Development'), ('IncidentReportApprover', 'IncidentReportApprover'), ('Installer', 'Installer'), ('Instant', 'Instant'), ('Internal', 'Internal'), ('KnownSigner', 'KnownSigner'), ('Module', 'Module'), ('Normal', 'Normal'), ('OEM', 'OEM'), ('Pre23', 'Pre23'), ('Preinstalled', 'Preinstalled'), ('Privileged', 'Privileged'), ('Recents', 'Recents'), ('RetailDemo', 'RetailDemo'), ('Role', 'Role'), ('Runtime', 'Runtime'), ('Setup', 'Setup'), ('Signature', 'Signature'), ('SignatureOrSystem', 'SignatureOrSystem'), ('System', 'System'), ('TextClassifier', 'TextClassifier'), ('VendorPrivileged', 'VendorPrivileged'), ('Verifier', 'Verifier')], default=mastf.MASTF.utils.enum.ProtectionLevel['NORMAL'], max_length=256),
        ),
        migrations.DeleteModel(
            name='ConnectionInfo',
        ),
    ]
