# Generated by Django 4.1.7 on 2023-03-23 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0004_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('severity', models.CharField(max_length=256, null=True)),
                ('format_keys', models.CharField(max_length=4096, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scanner',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='finding_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='scan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.project')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(max_length=256, null=True)),
                ('severity', models.IntegerField(default=0)),
                ('source_file', models.CharField(max_length=256, null=True)),
                ('source_line', models.CharField(max_length=256, null=True)),
                ('discovery_date', models.DateField(null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.scan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
