# Generated by Django 4.1.7 on 2023-03-24 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MASTF', '0006_alter_scan_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='duration',
        ),
        migrations.AddField(
            model_name='scan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=256, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
