# Generated by Django 4.1.7 on 2023-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0006_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
