# Generated by Django 4.1.7 on 2023-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0007_alter_component_is_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='url',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
