# Generated by Django 4.1.7 on 2023-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0007_remove_scan_duration_scan_end_date_accountdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
