# Generated by Django 4.1.7 on 2023-04-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0008_alter_finding_scanner_alter_vulnerability_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.projectscanner')),
            ],
        ),
    ]
