# Generated by Django 4.1.7 on 2023-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0008_alter_host_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
