# Generated by Django 4.1.7 on 2023-04-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0002_alter_package_type'),
        ('MASTF', '0009_alter_host_url'),
    ]

    operations = [
    ]
