# Generated by Django 4.1.7 on 2023-03-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0011_vulnerability_template_alter_finding_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256, null=True)),
                ('protection_level', models.CharField(blank=True, max_length=256)),
                ('dangerous', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=256, null=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('source', models.CharField(max_length=512, null=True)),
                ('risk', models.CharField(max_length=8192, null=True)),
            ],
        ),
    ]
