# Generated by Django 4.1.7 on 2023-04-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0011_remove_scantask_id_scantask_task_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvss', models.FloatField(default=0)),
                ('tracker_count', models.IntegerField(default=0)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.file')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
            ],
        ),
    ]
