# Generated by Django 4.1.7 on 2023-04-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0011_hosttemplate_remove_host_domain_remove_host_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan'),
        ),
    ]
