# Generated by Django 4.1.7 on 2023-03-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0013_alter_finding_severity_alter_vulnerability_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(blank=True, max_length=256)),
                ('language', models.CharField(max_length=256, null=True)),
                ('severity', models.CharField(max_length=32)),
                ('source_file', models.CharField(max_length=256, null=True)),
                ('source_line', models.CharField(max_length=256, null=True)),
                ('discovery_date', models.DateField(null=True)),
                ('scanner', models.CharField(max_length=256, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.permission')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.scan')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.findingtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
