# Generated by Django 4.1.7 on 2023-04-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0013_remove_details_scan_details_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='project',
        ),
        migrations.AddField(
            model_name='details',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan'),
        ),
    ]
