# Generated by Django 4.1.7 on 2023-03-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0014_permissionfinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.scan')),
            ],
        ),
    ]
