# Generated by Django 4.1.7 on 2023-04-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0014_remove_details_project_details_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.projectscanner'),
        ),
        migrations.CreateModel(
            name='PermissionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.apppermission')),
            ],
        ),
    ]
