# Generated by Django 4.1.7 on 2023-04-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0015_alter_scantask_scanner_permissionfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionfinding',
            name='discovery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='finding_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='language',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan'),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.projectscanner'),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='severity',
            field=models.CharField(default='INFO', max_length=32),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='source_file',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='source_line',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.findingtemplate'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(default='INFO', max_length=32),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(default='INFO', max_length=32),
        ),
    ]
