# Generated by Django 4.1.7 on 2023-03-28 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0015_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(max_length=256, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MASTF.project')),
            ],
        ),
    ]
