# Generated by Django 4.1.7 on 2023-04-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0015_packagevulnerability_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='license',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='outdated',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
