# Generated by Django 4.1.7 on 2023-04-30 05:20

from django.db import migrations, models
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0016_alter_dependency_license_alter_dependency_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular'), ('External', 'External')], default=mastf.MASTF.utils.enum.Role['REGULAR'], max_length=256),
        ),
    ]
