# Generated by Django 4.1.7 on 2023-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0016_permissionfinding_discovery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='internal_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
