# Generated by Django 4.1.7 on 2023-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0017_file_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingtemplate',
            name='article',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source_file',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source_line',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='source_file',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='source_line',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='source_file',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='source_line',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
