# Generated by Django 4.1.7 on 2023-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0018_rename_ip_adress_hosttemplate_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.UUIDField(primary_key=True, serialize=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('allow_teams', models.BooleanField(default=True)),
                ('max_projects', models.IntegerField(default=10000)),
                ('max_teams', models.IntegerField(default=10000)),
                ('max_bundles', models.IntegerField(default=10000)),
            ],
        ),
    ]
