# Generated by Django 4.1.7 on 2023-04-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0018_findingtemplate_article_alter_finding_source_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.CharField(blank=True, max_length=2048)),
                ('sys_path', models.CharField(max_length=1024, null=True)),
                ('language', models.CharField(max_length=32, null=True)),
                ('file_name', models.CharField(max_length=256, null=True)),
                ('file_size', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='finding',
            name='language',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='language',
        ),
        migrations.AddField(
            model_name='finding',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet'),
        ),
        migrations.AddField(
            model_name='permissionfinding',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.snippet'),
        ),
    ]
