# Generated by Django 4.1.7 on 2023-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0019_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='first_start',
            field=models.BooleanField(default=True),
        ),
    ]
