# Generated by Django 4.1.7 on 2023-04-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0019_snippet_remove_finding_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='source_line',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='source_line',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='source_line',
        ),
    ]
