# Generated by Django 4.1.7 on 2023-04-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mastf.MASTF.utils.enum


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MASTF', '0020_remove_finding_source_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='id',
        ),
        migrations.RemoveField(
            model_name='findingtemplate',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='permissionfinding',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='id',
        ),
        migrations.AddField(
            model_name='findingtemplate',
            name='default_severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='finding',
            name='finding_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='finding_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='inspection_type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Advanced', 'Advanced')], default=mastf.MASTF.utils.enum.InspectionType['SIMPLE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='risk_level',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['INFO'], max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=mastf.MASTF.utils.enum.Visibility['PRIVATE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='file_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='finding_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Info'), ('Secure', 'Secure'), ('None', 'None')], default=mastf.MASTF.utils.enum.Severity['NONE'], max_length=256),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='state',
            field=models.CharField(choices=[('To Verify', 'To Verify'), ('Confirmed', 'Confirmed'), ('Urgent', 'Urgent'), ('Not Exploitable', 'Not Exploitable'), ('Proposed not exploitable', 'Proposed not exploitable')], default=mastf.MASTF.utils.enum.State['TO_VERIFY'], max_length=256),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Internal', 'Internal')], default=mastf.MASTF.utils.enum.Visibility['PUBLIC'], max_length=256)),
                ('users', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scan')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.team'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MASTF.scanner'),
        ),
        migrations.DeleteModel(
            name='ProjectScanner',
        ),
    ]
