# Generated by Django 4.1.7 on 2023-05-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0020_environment_first_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='protection_level',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
