# Generated by Django 4.1.7 on 2023-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0021_alter_apppermission_protection_level_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='artifact_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='group_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
