# Generated by Django 4.1.7 on 2023-05-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0025_findingtemplate_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.findingtemplate'),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='permissionfinding',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.findingtemplate'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='scanner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.scanner'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MASTF.findingtemplate'),
        ),
    ]
