# Generated by Django 4.1.7 on 2023-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASTF', '0027_alter_apppermission_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='type',
            new_name='package_type',
        ),
        migrations.AddField(
            model_name='finding',
            name='custom_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='identifier',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='max_projects',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='findingtemplate',
            name='internal_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='findingtemplate',
            name='template_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
