# Generated by Django 4.2.1 on 2023-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MASTF", "0030_certificate_apppermission_created_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=1024)),
                ("action", models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="details",
            name="file",
        ),
        migrations.AddField(
            model_name="component",
            name="is_launcher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="component",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="details",
            name="app_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="app_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="app_version",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="certificates",
            field=models.ManyToManyField(
                related_name="details", to="MASTF.certificate"
            ),
        ),
        migrations.AddField(
            model_name="details",
            name="icon",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="details",
            name="target_sdk",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="category",
            field=models.CharField(
                choices=[
                    ("Activity", "Activity"),
                    ("Service", "Service"),
                    ("Receiver", "Receiver"),
                    ("Provider", "Provider"),
                    ("View", "View"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="is_protected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="component",
            name="intent_filters",
            field=models.ManyToManyField(
                related_name="components", to="MASTF.intentfilter"
            ),
        ),
    ]
