# Insecure SSL
- rule-id: android-insecure-ssl-allowallhostnameverifier
  patterns:
    - javax\.net\.ssl
    - AllTrustSSLSocketFactory\|NonValidatingSSLSocketFactory\|ALLOW_ALL_HOSTNAME_VERIFIER|\.setDefaultHostnameVerifier\(|NullHostnameVerifier\(
  meta:
    filter:
      file_ext: java
    severity: high
    template: insecure-implementation-of-ssl-with-allowallhostnameverifier
    vulnerability: true

- rule-id: android-insecure-ssl-trustmanager-ignore-certificate-validation
  patterns:
    - javax\.net\.ssl
    - public\s*X509Certificate\[\]\s*getAcceptedIssuers\s*\(\s*\)?
    - return\s*null\s*
  meta:
    filter:
      file_ext: java
    severity: critical
    template: insecure-implementation-of-ssl-with-trustmanager-ignoring-certificate-validation
    vulnerability: false

- rule-id: android-insecure-ssl-trustmanager-accept-all-certificates
  patterns:
    - javax\.net\.ssl
    - mode: or
      text: (SSLSocketFactory|HttpsURLConnection)\s*\.\s*setHostnameVerifier\s*\(\s*AllowAllHostnameVerifier\s*\.\s*INSTANCE\s*\)\s*\.\s*setTrustAllCerts\s*\(\s*true\s*\)
    - mode: or
      text: \.\s*setTrustAllCerts\s*\(\s*true\s*\)
  meta:
    filter:
      file_ext: java
    severity: critical
    template: insecure-implementation-of-ssl-with-trustmanager-accepting-all-certificates
    vulnerability: true

- rule-id: android-insecure-ssl-weak-cipher-suites
  patterns:
    - javax\.net\.ssl
    - (SSLSocketFactory|HttpsURLConnection)\s*\.\s*setEnabledCipherSuites\s*\(\s*new\s*String\[\]\s*{\s*".*DES.*|.*RC4.*"
  meta:
    filter:
      file_ext: java
    severity: high
    template: insecure-implementation-of-ssl-with-weak-cipher-suites
    vulnerability: false

- rule-id: android-insecure-ssl-sslv3-or-tlsv1
  patterns:
    - javax\.net\.ssl
    - setEnabledProtocols\s*\(\s*new\s*String\[\]\s*{\s*("SSLv3"|.*TLSv1.*)
  meta:
    filter:
      file_ext: java
    severity:
    template: insecure-implementation-of-ssl-with-sslv3-or-tlsv1
    vulnerability: true

# Insecure Random
- rule-id: android-insecure-random-java
  patterns:
    - java\.util\.Random
    - new\s*Random\(
  meta:
    filter:
      file_ext: java, kt
    severity: high
    template: insecure-use-of-random-number-generator-(java.util.random)
    vulnerability: false

- rule-id: android-insecure-random-android
  patterns:
    - android\.util\.Random
    - new\s*Random\(
  meta:
    filter:
      file_ext: java, kt
    severity: high
    template: insecure-use-of-random-number-generator-(android.util.random)
    vulnerability: false

# Logging
- rule-id: android-logging-sensitive-information
  pattern: \b(Log\.[vdiew]|System\.out\.println)\s*\(\s*\".*(?:password|api[_ ]key|pii|personally[_ ]identifiable[_ ]information).*\"
  meta:
    filter:
      file_ext: java, kt
    severity: high
    template: insecure-logging-of-sensitive-information
    vulnerability: false

- rule-id: android-logging-debug-messages-in-release-build
  pattern: \b(Log\.[vdiew]|System\.out\.println)\s*\(\s*\".*\"\s*,\s*.*\bBuildConfig\.DEBUG\b
  meta:
    filter:
      file_ext: java, kt
    severity: high
    template: insecure-logging-of-debug-messages-in-release-build
    vulnerability: false

- rule-id: android-logging-exceptions
  pattern: \b(Log\.[vdiew]|System\.out\.println)\s*\(\s*.*\bException\b.*
  meta:
    filter:
      file_ext: java, kt
    severity: medium
    template: insecure-logging-of-exceptions
    vulnerability: false

# temporary Files
- rule-id: android-temporary-file-(java.io.file)
  patterns:
    - java\.io\.File
    - \bnew\s+File\s*\(\s*.*(?:File|createNewFile|createTempFile)
  meta:
    filter:
      file_ext: java, kt
    severity: medium
    template: creation-of-temporary-file-(java.io.file)
    vulnerability: false

- rule-id: android-temporary-file-(java.io.fileoutputstream)
  patterns:
    - java\.io\.FileOutputStream
    - \bnew\s+FileOutputStream\s*\(\s*.*(?:File|createNewFile)
  meta:
    filter:
      file_ext: java, kt
    severity: medium
    template: creation-of-temporary-file-(java.io.fileoutputstream)
    vulnerability: false

- rule-id: android-temporary-file-(android.content.contextwrapper)
  patterns:
    - android\.content\.ContextWrapper
    - \bnew\s+ContextWrapper\s*\(\s*.*(?:File|createNewFile).*\)
  meta:
    filter:
      file_ext: java, kt
    severity: medium
    template: creation-of-temporary-file-(android.content.contextwrapper)
    vulnerability: false
